version: '3'

services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - './src:/var/www/html'
  
  nginx: 
    image: nginx:latest
    ports: 
      - 80:80
    volumes: 
      - './src:/usr/share/nginx/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
  
  mysql:
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: movie
      MYSQL_ROOT_PASSWORD: root
    ports:
          - "33061:3306"
